### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/rccc1310/Makefile.srf06

CONTIKI_TARGET_DIRS += rccc1310/cc13xx
